[[mgr.prepend_keymap]]
on = [ "c", "a" ]
run = "plugin ouch"
desc = "Create archive (ouch)"

[[mgr.append_keymap]]
# Copy
on = [ "c", "k" ]
run = "shell 'cat $0 | wl-copy' --confirm"
desc = "Copy the file content"
